sonar.projectKey=itamaraharon_sample-nodejs
sonar.organization=itamaraharon
sonar.sources=.
sonar.exclusions=node_modules/**,**/*.test.js,coverage/**
sonar.tests=tests
sonar.javascript.lcov.reportPaths=coverage/lcov.info
